DROP TABLE IF EXISTS CRIMES;

CREATE TABLE CRIMES (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100),
    DESCRICAO TEXT,
    DATA_CRIME DATE,
    HEROI_RESPONSAVEL INT REFERENCES HEROI(CODIGO_HEROI) ON DELETE CASCADE,
    SEVERIDADE INT,
    OCULTO BOOLEAN DEFAULT FALSE
);

SELECT * FROM CRIMES;

ALTER TABLE CRIMES ALTER COLUMN SEVERIDADE TYPE TEXT;

ALTER TABLE CRIMES DROP CONSTRAINT CRIMES_HEROI_RESPONSAVEL_FKEY;

ALTER TABLE CRIMES
ADD CONSTRAINT CRIMES_HEROI_RESPONSAVEL_FKEY
FOREIGN KEY (HEROI_RESPONSAVEL) REFERENCES heroi(CODIGO_HEROI) ON DELETE CASCADE;

delete from CRIMES;
