DROP TABLE IF MISSOES EXISTS

CREATE TABLE MISSOES (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    CLASSIFICACAO VARCHAR(50),
    DIFICULDADE INT CHECK (dificuldade >= 1 AND dificuldade <= 10),
    HEROIS TEXT[]
);