DROP TABLE IF EXISTS crimes;

CREATE TABLE CRIMES (
    ID SERIAL PRIMARY KEY,
    NOME_CRIME VARCHAR(100),
    DESCRICAO TEXT,
    DATA_CRIME DATE,
    HEROI_RESPONSAVEL INT,
    SEVERIDADE INT
);
SELECT * FROM CRIMES;
ALTER TABLE CRIMES ALTER COLUMN SEVERIDADE TYPE TEXT;

ALTER TABLE CRIMES ADD COLUMN OCULTO BOOLEAN DEFAULT FALSE;

CREATE TABLE HISTORICO_OCULTACAO (
    ID SERIAL PRIMARY KEY,
    ID_CRIME INT,
    CODIGO_HEROI INT,
    DATA_OCULTACAO TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (ID_CRIME) REFERENCES CRIMES(ID),
    FOREIGN KEY (CODIGO_HEROI) REFERENCES HEROI(CODIGO_HEROI)
);


